export enum RouteName {
  activityView = "/activity",
  auctionsView = "/auctions",
  home = "/",
  marketplace = "/marketplace",
  marketplaceMint = "/marketplace/:tokenMint",
  sell = "/sell",
  customToken = "/custom-token-marketplace",
  multipleCollection = "/multi-collection-marketplace",
  marketplaceWithUrl = "/marketplace-with-url",
  multipleCurrencyMarketplace = "/multi-currency-marketplace",
  multipleCurrencySell = "/multi-currency-sell",
  magicEden = "https://magiceden.io/marketplace/gatsbyclub/",
  raydium = "https://raydium.io/swap/?inputCurrency=sol&outputCurrency=99Q3AfFWX3rdidoQCnAPPoZFjsaXr2AAk65RUgxiwfUi&inputAmount=0&outputAmount=0&fixed=in",
}
